package com.thelak.database.entity.auto;

import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbArticle;

/**
 * Class _DbArticleRating was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbArticleRating extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<LocalDateTime> CREATED_DATE = Property.create("createdDate", LocalDateTime.class);
    public static final Property<LocalDateTime> DELETED_DATE = Property.create("deletedDate", LocalDateTime.class);
    public static final Property<Long> ID_USER = Property.create("idUser", Long.class);
    public static final Property<LocalDateTime> MIDIFIED_DATE = Property.create("midifiedDate", LocalDateTime.class);
    public static final Property<Integer> SCORE = Property.create("score", Integer.class);
    public static final Property<DbArticle> RATING_TO_ARTICLE = Property.create("ratingToArticle", DbArticle.class);

    public void setCreatedDate(LocalDateTime createdDate) {
        writeProperty("createdDate", createdDate);
    }
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime)readProperty("createdDate");
    }

    public void setDeletedDate(LocalDateTime deletedDate) {
        writeProperty("deletedDate", deletedDate);
    }
    public LocalDateTime getDeletedDate() {
        return (LocalDateTime)readProperty("deletedDate");
    }

    public void setIdUser(long idUser) {
        writeProperty("idUser", idUser);
    }
    public long getIdUser() {
        Object value = readProperty("idUser");
        return (value != null) ? (Long) value : 0;
    }

    public void setMidifiedDate(LocalDateTime midifiedDate) {
        writeProperty("midifiedDate", midifiedDate);
    }
    public LocalDateTime getMidifiedDate() {
        return (LocalDateTime)readProperty("midifiedDate");
    }

    public void setScore(int score) {
        writeProperty("score", score);
    }
    public int getScore() {
        Object value = readProperty("score");
        return (value != null) ? (Integer) value : 0;
    }

    public void setRatingToArticle(DbArticle ratingToArticle) {
        setToOneTarget("ratingToArticle", ratingToArticle, true);
    }

    public DbArticle getRatingToArticle() {
        return (DbArticle)readProperty("ratingToArticle");
    }


}
