package com.thelak.database.entity.auto;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbIssuedCertificate;
import com.thelak.database.entity.DbOptionCertificate;

/**
 * Class _DbCertificate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbCertificate extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> COVER = Property.create("cover", Integer.class);
    public static final Property<LocalDateTime> CREATED_DATE = Property.create("createdDate", LocalDateTime.class);
    public static final Property<LocalDateTime> DELETED_DATE = Property.create("deletedDate", LocalDateTime.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<String> LENGTH = Property.create("length", String.class);
    public static final Property<LocalDateTime> MODIFIED_DATE = Property.create("modifiedDate", LocalDateTime.class);
    public static final Property<Integer> MONTHS = Property.create("months", Integer.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<Integer> PRICE = Property.create("price", Integer.class);
    public static final Property<String> PRICE_STR = Property.create("priceStr", String.class);
    public static final Property<String> PRICE_STR2 = Property.create("priceStr2", String.class);
    public static final Property<List<DbIssuedCertificate>> CERTIFICATE_TO_ISSUED = Property.create("certificateToIssued", List.class);
    public static final Property<List<DbOptionCertificate>> CERTIFICATE_TO_OPTION = Property.create("certificateToOption", List.class);

    public void setCover(int cover) {
        writeProperty("cover", cover);
    }
    public int getCover() {
        Object value = readProperty("cover");
        return (value != null) ? (Integer) value : 0;
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        writeProperty("createdDate", createdDate);
    }
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime)readProperty("createdDate");
    }

    public void setDeletedDate(LocalDateTime deletedDate) {
        writeProperty("deletedDate", deletedDate);
    }
    public LocalDateTime getDeletedDate() {
        return (LocalDateTime)readProperty("deletedDate");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setLength(String length) {
        writeProperty("length", length);
    }
    public String getLength() {
        return (String)readProperty("length");
    }

    public void setModifiedDate(LocalDateTime modifiedDate) {
        writeProperty("modifiedDate", modifiedDate);
    }
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime)readProperty("modifiedDate");
    }

    public void setMonths(int months) {
        writeProperty("months", months);
    }
    public int getMonths() {
        Object value = readProperty("months");
        return (value != null) ? (Integer) value : 0;
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPrice(int price) {
        writeProperty("price", price);
    }
    public int getPrice() {
        Object value = readProperty("price");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPriceStr(String priceStr) {
        writeProperty("priceStr", priceStr);
    }
    public String getPriceStr() {
        return (String)readProperty("priceStr");
    }

    public void setPriceStr2(String priceStr2) {
        writeProperty("priceStr2", priceStr2);
    }
    public String getPriceStr2() {
        return (String)readProperty("priceStr2");
    }

    public void addToCertificateToIssued(DbIssuedCertificate obj) {
        addToManyTarget("certificateToIssued", obj, true);
    }
    public void removeFromCertificateToIssued(DbIssuedCertificate obj) {
        removeToManyTarget("certificateToIssued", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbIssuedCertificate> getCertificateToIssued() {
        return (List<DbIssuedCertificate>)readProperty("certificateToIssued");
    }


    public void addToCertificateToOption(DbOptionCertificate obj) {
        addToManyTarget("certificateToOption", obj, true);
    }
    public void removeFromCertificateToOption(DbOptionCertificate obj) {
        removeToManyTarget("certificateToOption", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbOptionCertificate> getCertificateToOption() {
        return (List<DbOptionCertificate>)readProperty("certificateToOption");
    }


}
