package com.thelak.database.entity.auto;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbIssuedCertificate;
import com.thelak.database.entity.DbOptionCertificate;
import com.thelak.database.entity.DbPayments;

/**
 * Class _DbCards was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbCards extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<LocalDateTime> CREATED_DATE = Property.create("createdDate", LocalDateTime.class);
    public static final Property<Integer> CVV = Property.create("cvv", Integer.class);
    public static final Property<LocalDateTime> DELETED_DATE = Property.create("deletedDate", LocalDateTime.class);
    public static final Property<Long> ID_USER = Property.create("idUser", Long.class);
    public static final Property<LocalDateTime> MODIFIED_DATE = Property.create("modifiedDate", LocalDateTime.class);
    public static final Property<Integer> MONTH = Property.create("month", Integer.class);
    public static final Property<Integer> NUMBER = Property.create("number", Integer.class);
    public static final Property<String> OWNER = Property.create("owner", String.class);
    public static final Property<Integer> YEAR = Property.create("year", Integer.class);
    public static final Property<List<DbPayments>> CARD_TO_PAYMENT = Property.create("cardToPayment", List.class);
    public static final Property<List<DbIssuedCertificate>> CERTIFICATE_TO_ISSUED = Property.create("certificateToIssued", List.class);
    public static final Property<List<DbOptionCertificate>> CERTIFICATE_TO_OPTION = Property.create("certificateToOption", List.class);

    public void setCreatedDate(LocalDateTime createdDate) {
        writeProperty("createdDate", createdDate);
    }
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime)readProperty("createdDate");
    }

    public void setCvv(int cvv) {
        writeProperty("cvv", cvv);
    }
    public int getCvv() {
        Object value = readProperty("cvv");
        return (value != null) ? (Integer) value : 0;
    }

    public void setDeletedDate(LocalDateTime deletedDate) {
        writeProperty("deletedDate", deletedDate);
    }
    public LocalDateTime getDeletedDate() {
        return (LocalDateTime)readProperty("deletedDate");
    }

    public void setIdUser(long idUser) {
        writeProperty("idUser", idUser);
    }
    public long getIdUser() {
        Object value = readProperty("idUser");
        return (value != null) ? (Long) value : 0;
    }

    public void setModifiedDate(LocalDateTime modifiedDate) {
        writeProperty("modifiedDate", modifiedDate);
    }
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime)readProperty("modifiedDate");
    }

    public void setMonth(int month) {
        writeProperty("month", month);
    }
    public int getMonth() {
        Object value = readProperty("month");
        return (value != null) ? (Integer) value : 0;
    }

    public void setNumber(int number) {
        writeProperty("number", number);
    }
    public int getNumber() {
        Object value = readProperty("number");
        return (value != null) ? (Integer) value : 0;
    }

    public void setOwner(String owner) {
        writeProperty("owner", owner);
    }
    public String getOwner() {
        return (String)readProperty("owner");
    }

    public void setYear(int year) {
        writeProperty("year", year);
    }
    public int getYear() {
        Object value = readProperty("year");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToCardToPayment(DbPayments obj) {
        addToManyTarget("cardToPayment", obj, true);
    }
    public void removeFromCardToPayment(DbPayments obj) {
        removeToManyTarget("cardToPayment", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbPayments> getCardToPayment() {
        return (List<DbPayments>)readProperty("cardToPayment");
    }


    public void addToCertificateToIssued(DbIssuedCertificate obj) {
        addToManyTarget("certificateToIssued", obj, true);
    }
    public void removeFromCertificateToIssued(DbIssuedCertificate obj) {
        removeToManyTarget("certificateToIssued", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbIssuedCertificate> getCertificateToIssued() {
        return (List<DbIssuedCertificate>)readProperty("certificateToIssued");
    }


    public void addToCertificateToOption(DbOptionCertificate obj) {
        addToManyTarget("certificateToOption", obj, true);
    }
    public void removeFromCertificateToOption(DbOptionCertificate obj) {
        removeToManyTarget("certificateToOption", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbOptionCertificate> getCertificateToOption() {
        return (List<DbOptionCertificate>)readProperty("certificateToOption");
    }


}
