package com.thelak.database.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbCategory;

/**
 * Class _DbCategoryVideos was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbCategoryVideos extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ID_VIDEO = Property.create("idVideo", Long.class);
    public static final Property<DbCategory> VIDEO_TO_CATEGORY = Property.create("videoToCategory", DbCategory.class);

    public void setIdVideo(long idVideo) {
        writeProperty("idVideo", idVideo);
    }
    public long getIdVideo() {
        Object value = readProperty("idVideo");
        return (value != null) ? (Long) value : 0;
    }

    public void setVideoToCategory(DbCategory videoToCategory) {
        setToOneTarget("videoToCategory", videoToCategory, true);
    }

    public DbCategory getVideoToCategory() {
        return (DbCategory)readProperty("videoToCategory");
    }


}
