package com.thelak.database.entity.auto;

import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbCertificate;

/**
 * Class _DbIssuedCertificate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbIssuedCertificate extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> ACTIVE = Property.create("active", Boolean.class);
    public static final Property<LocalDateTime> ACTIVE_DATE = Property.create("activeDate", LocalDateTime.class);
    public static final Property<LocalDateTime> CREATED_DATE = Property.create("createdDate", LocalDateTime.class);
    public static final Property<LocalDateTime> DELETED_DATE = Property.create("deletedDate", LocalDateTime.class);
    public static final Property<String> FIO = Property.create("fio", String.class);
    public static final Property<LocalDateTime> MODIFIED_DATE = Property.create("modifiedDate", LocalDateTime.class);
    public static final Property<String> UUID = Property.create("uuid", String.class);
    public static final Property<DbCertificate> ISSUED_TO_CERTIFICATE = Property.create("issuedToCertificate", DbCertificate.class);

    public void setActive(boolean active) {
        writeProperty("active", active);
    }
	public boolean isActive() {
        Boolean value = (Boolean)readProperty("active");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setActiveDate(LocalDateTime activeDate) {
        writeProperty("activeDate", activeDate);
    }
    public LocalDateTime getActiveDate() {
        return (LocalDateTime)readProperty("activeDate");
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        writeProperty("createdDate", createdDate);
    }
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime)readProperty("createdDate");
    }

    public void setDeletedDate(LocalDateTime deletedDate) {
        writeProperty("deletedDate", deletedDate);
    }
    public LocalDateTime getDeletedDate() {
        return (LocalDateTime)readProperty("deletedDate");
    }

    public void setFio(String fio) {
        writeProperty("fio", fio);
    }
    public String getFio() {
        return (String)readProperty("fio");
    }

    public void setModifiedDate(LocalDateTime modifiedDate) {
        writeProperty("modifiedDate", modifiedDate);
    }
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime)readProperty("modifiedDate");
    }

    public void setUuid(String uuid) {
        writeProperty("uuid", uuid);
    }
    public String getUuid() {
        return (String)readProperty("uuid");
    }

    public void setIssuedToCertificate(DbCertificate issuedToCertificate) {
        setToOneTarget("issuedToCertificate", issuedToCertificate, true);
    }

    public DbCertificate getIssuedToCertificate() {
        return (DbCertificate)readProperty("issuedToCertificate");
    }


}
