package com.thelak.database.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbCertificate;
import com.thelak.database.entity.DbOptions;

/**
 * Class _DbOptionCertificate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbOptionCertificate extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<DbCertificate> OPSUB_TO_CERTIFICATE = Property.create("opsubToCertificate", DbCertificate.class);
    public static final Property<DbOptions> OPSUB_TO_OPTIONS = Property.create("opsubToOptions", DbOptions.class);

    public void setOpsubToCertificate(DbCertificate opsubToCertificate) {
        setToOneTarget("opsubToCertificate", opsubToCertificate, true);
    }

    public DbCertificate getOpsubToCertificate() {
        return (DbCertificate)readProperty("opsubToCertificate");
    }


    public void setOpsubToOptions(DbOptions opsubToOptions) {
        setToOneTarget("opsubToOptions", opsubToOptions, true);
    }

    public DbOptions getOpsubToOptions() {
        return (DbOptions)readProperty("opsubToOptions");
    }


}
