package com.thelak.database.entity.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbCertificate;
import com.thelak.database.entity.DbOptions;

/**
 * Class _DbOptionCertificate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbOptionCertificate extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<DbCertificate> OPSUB_TO_CERTIFICATE = Property.create("opsubToCertificate", DbCertificate.class);
    public static final Property<DbOptions> OPSUB_TO_OPTIONS = Property.create("opsubToOptions", DbOptions.class);


    protected Object opsubToCertificate;
    protected Object opsubToOptions;

    public void setOpsubToCertificate(DbCertificate opsubToCertificate) {
        setToOneTarget("opsubToCertificate", opsubToCertificate, true);
    }

    public DbCertificate getOpsubToCertificate() {
        return (DbCertificate)readProperty("opsubToCertificate");
    }

    public void setOpsubToOptions(DbOptions opsubToOptions) {
        setToOneTarget("opsubToOptions", opsubToOptions, true);
    }

    public DbOptions getOpsubToOptions() {
        return (DbOptions)readProperty("opsubToOptions");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "opsubToCertificate":
                return this.opsubToCertificate;
            case "opsubToOptions":
                return this.opsubToOptions;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "opsubToCertificate":
                this.opsubToCertificate = val;
                break;
            case "opsubToOptions":
                this.opsubToOptions = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.opsubToCertificate);
        out.writeObject(this.opsubToOptions);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.opsubToCertificate = in.readObject();
        this.opsubToOptions = in.readObject();
    }

}
