package com.thelak.database.entity.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbOptionSubscription;

/**
 * Class _DbOptions was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbOptions extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> TEXT = Property.create("text", String.class);
    public static final Property<List<DbOptionSubscription>> OPTIONS_TO_OPSUB = Property.create("optionsToOpsub", List.class);

    public void setText(String text) {
        writeProperty("text", text);
    }
    public String getText() {
        return (String)readProperty("text");
    }

    public void addToOptionsToOpsub(DbOptionSubscription obj) {
        addToManyTarget("optionsToOpsub", obj, true);
    }
    public void removeFromOptionsToOpsub(DbOptionSubscription obj) {
        removeToManyTarget("optionsToOpsub", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbOptionSubscription> getOptionsToOpsub() {
        return (List<DbOptionSubscription>)readProperty("optionsToOpsub");
    }


}
