package com.thelak.database.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbOptions;
import com.thelak.database.entity.DbSubscription;

/**
 * Class _DbOptionSubscription was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbOptionSubscription extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<DbOptions> OPSUB_TO_OPTIONS = Property.create("opsubToOptions", DbOptions.class);
    public static final Property<DbSubscription> OPSUB_TO_SUBSCRIPTION = Property.create("opsubToSubscription", DbSubscription.class);

    public void setOpsubToOptions(DbOptions opsubToOptions) {
        setToOneTarget("opsubToOptions", opsubToOptions, true);
    }

    public DbOptions getOpsubToOptions() {
        return (DbOptions)readProperty("opsubToOptions");
    }


    public void setOpsubToSubscription(DbSubscription opsubToSubscription) {
        setToOneTarget("opsubToSubscription", opsubToSubscription, true);
    }

    public DbSubscription getOpsubToSubscription() {
        return (DbSubscription)readProperty("opsubToSubscription");
    }


}
