package com.thelak.database.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbPromo;

/**
 * Class _DbPromoEmail was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbPromoEmail extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> EMAIL = Property.create("email", String.class);
    public static final Property<DbPromo> EMAIL_TO_PROMO = Property.create("emailToPromo", DbPromo.class);

    public void setEmail(String email) {
        writeProperty("email", email);
    }
    public String getEmail() {
        return (String)readProperty("email");
    }

    public void setEmailToPromo(DbPromo emailToPromo) {
        setToOneTarget("emailToPromo", emailToPromo, true);
    }

    public DbPromo getEmailToPromo() {
        return (DbPromo)readProperty("emailToPromo");
    }


}
