package com.thelak.database.entity.auto;

import java.time.LocalDateTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbCards;
import com.thelak.database.entity.DbPaymentType;

/**
 * Class _DbPayments was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbPayments extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<LocalDateTime> CREATED_DATE = Property.create("createdDate", LocalDateTime.class);
    public static final Property<LocalDateTime> DELETED_DATE = Property.create("deletedDate", LocalDateTime.class);
    public static final Property<String> ID_USER = Property.create("idUser", String.class);
    public static final Property<LocalDateTime> MODIFIED_DATE = Property.create("modifiedDate", LocalDateTime.class);
    public static final Property<Integer> SUM = Property.create("sum", Integer.class);
    public static final Property<DbCards> PAYMENT_TO_CARD = Property.create("paymentToCard", DbCards.class);
    public static final Property<DbPaymentType> PAYMENT_TO_TYPE = Property.create("paymentToType", DbPaymentType.class);

    public void setCreatedDate(LocalDateTime createdDate) {
        writeProperty("createdDate", createdDate);
    }
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime)readProperty("createdDate");
    }

    public void setDeletedDate(LocalDateTime deletedDate) {
        writeProperty("deletedDate", deletedDate);
    }
    public LocalDateTime getDeletedDate() {
        return (LocalDateTime)readProperty("deletedDate");
    }

    public void setIdUser(String idUser) {
        writeProperty("idUser", idUser);
    }
    public String getIdUser() {
        return (String)readProperty("idUser");
    }

    public void setModifiedDate(LocalDateTime modifiedDate) {
        writeProperty("modifiedDate", modifiedDate);
    }
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime)readProperty("modifiedDate");
    }

    public void setSum(int sum) {
        writeProperty("sum", sum);
    }
    public int getSum() {
        Object value = readProperty("sum");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPaymentToCard(DbCards paymentToCard) {
        setToOneTarget("paymentToCard", paymentToCard, true);
    }

    public DbCards getPaymentToCard() {
        return (DbCards)readProperty("paymentToCard");
    }


    public void setPaymentToType(DbPaymentType paymentToType) {
        setToOneTarget("paymentToType", paymentToType, true);
    }

    public DbPaymentType getPaymentToType() {
        return (DbPaymentType)readProperty("paymentToType");
    }


}
