package com.thelak.database.entity.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbPayments;

/**
 * Class _DbPaymentType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbPaymentType extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> TEXT = Property.create("text", String.class);
    public static final Property<List<DbPayments>> TYPE_TO_PAYMENT = Property.create("typeToPayment", List.class);

    public void setText(String text) {
        writeProperty("text", text);
    }
    public String getText() {
        return (String)readProperty("text");
    }

    public void addToTypeToPayment(DbPayments obj) {
        addToManyTarget("typeToPayment", obj, true);
    }
    public void removeFromTypeToPayment(DbPayments obj) {
        removeToManyTarget("typeToPayment", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbPayments> getTypeToPayment() {
        return (List<DbPayments>)readProperty("typeToPayment");
    }


}
