package com.thelak.database.entity.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbPromoEmail;

/**
 * Class _DbPromo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbPromo extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> ACTIVE = Property.create("active", Boolean.class);
    public static final Property<String> CODE = Property.create("code", String.class);
    public static final Property<Integer> DAYS = Property.create("days", Integer.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<Integer> MONTHS = Property.create("months", Integer.class);
    public static final Property<List<DbPromoEmail>> PROMO_TO_EMAIL = Property.create("promoToEmail", List.class);

    public void setActive(boolean active) {
        writeProperty("active", active);
    }
	public boolean isActive() {
        Boolean value = (Boolean)readProperty("active");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setCode(String code) {
        writeProperty("code", code);
    }
    public String getCode() {
        return (String)readProperty("code");
    }

    public void setDays(int days) {
        writeProperty("days", days);
    }
    public int getDays() {
        Object value = readProperty("days");
        return (value != null) ? (Integer) value : 0;
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setMonths(int months) {
        writeProperty("months", months);
    }
    public int getMonths() {
        Object value = readProperty("months");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToPromoToEmail(DbPromoEmail obj) {
        addToManyTarget("promoToEmail", obj, true);
    }
    public void removeFromPromoToEmail(DbPromoEmail obj) {
        removeToManyTarget("promoToEmail", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbPromoEmail> getPromoToEmail() {
        return (List<DbPromoEmail>)readProperty("promoToEmail");
    }


}
