package com.thelak.database.entity.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbPaymentsCryptogramm;
import com.thelak.database.entity.DbPaymentsReccuring;
import com.thelak.database.entity.DbPaymentsReccurrent;

/**
 * Class _DbPaymentType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbPaymentType extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> TEXT = Property.create("text", String.class);
    public static final Property<List<DbPaymentsCryptogramm>> TYPE_TO_CRYPTOGRAMM_PAYMENT = Property.create("typeToCryptogrammPayment", List.class);
    public static final Property<List<DbPaymentsReccurrent>> TYPE_TO_RECCURENT = Property.create("typeToReccurent", List.class);
    public static final Property<List<DbPaymentsReccuring>> TYPE_TO_RECURRING = Property.create("typeToRecurring", List.class);

    public void setText(String text) {
        writeProperty("text", text);
    }
    public String getText() {
        return (String)readProperty("text");
    }

    public void addToTypeToCryptogrammPayment(DbPaymentsCryptogramm obj) {
        addToManyTarget("typeToCryptogrammPayment", obj, true);
    }
    public void removeFromTypeToCryptogrammPayment(DbPaymentsCryptogramm obj) {
        removeToManyTarget("typeToCryptogrammPayment", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbPaymentsCryptogramm> getTypeToCryptogrammPayment() {
        return (List<DbPaymentsCryptogramm>)readProperty("typeToCryptogrammPayment");
    }


    public void addToTypeToReccurent(DbPaymentsReccurrent obj) {
        addToManyTarget("typeToReccurent", obj, true);
    }
    public void removeFromTypeToReccurent(DbPaymentsReccurrent obj) {
        removeToManyTarget("typeToReccurent", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbPaymentsReccurrent> getTypeToReccurent() {
        return (List<DbPaymentsReccurrent>)readProperty("typeToReccurent");
    }


    public void addToTypeToRecurring(DbPaymentsReccuring obj) {
        addToManyTarget("typeToRecurring", obj, true);
    }
    public void removeFromTypeToRecurring(DbPaymentsReccuring obj) {
        removeToManyTarget("typeToRecurring", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbPaymentsReccuring> getTypeToRecurring() {
        return (List<DbPaymentsReccuring>)readProperty("typeToRecurring");
    }


}
