package com.thelak.database.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbSpeaker;

/**
 * Class _DbSpeakerArticles was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbSpeakerArticles extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ID_ARTICLE = Property.create("idArticle", Long.class);
    public static final Property<DbSpeaker> ARTICLE_TO_SPEAKER = Property.create("articleToSpeaker", DbSpeaker.class);

    public void setIdArticle(long idArticle) {
        writeProperty("idArticle", idArticle);
    }
    public long getIdArticle() {
        Object value = readProperty("idArticle");
        return (value != null) ? (Long) value : 0;
    }

    public void setArticleToSpeaker(DbSpeaker articleToSpeaker) {
        setToOneTarget("articleToSpeaker", articleToSpeaker, true);
    }

    public DbSpeaker getArticleToSpeaker() {
        return (DbSpeaker)readProperty("articleToSpeaker");
    }


}
