package com.thelak.database.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbSpeaker;

/**
 * Class _DbSpeakerVideos was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbSpeakerVideos extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Long> ID_VIDEO = Property.create("idVideo", Long.class);
    public static final Property<DbSpeaker> VIDEO_TO_SPEAKER = Property.create("videoToSpeaker", DbSpeaker.class);

    public void setIdVideo(long idVideo) {
        writeProperty("idVideo", idVideo);
    }
    public long getIdVideo() {
        Object value = readProperty("idVideo");
        return (value != null) ? (Long) value : 0;
    }

    public void setVideoToSpeaker(DbSpeaker videoToSpeaker) {
        setToOneTarget("videoToSpeaker", videoToSpeaker, true);
    }

    public DbSpeaker getVideoToSpeaker() {
        return (DbSpeaker)readProperty("videoToSpeaker");
    }


}
