package com.thelak.database.entity.auto;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbSpeakerArticles;
import com.thelak.database.entity.DbSpeakerEvents;
import com.thelak.database.entity.DbSpeakerVideos;

/**
 * Class _DbSpeaker was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbSpeaker extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> COUNTRY = Property.create("country", String.class);
    public static final Property<String> COUNTRY_FLAG_CODE = Property.create("countryFlagCode", String.class);
    public static final Property<LocalDateTime> CREATED_DATE = Property.create("createdDate", LocalDateTime.class);
    public static final Property<LocalDateTime> DELETED_DATE = Property.create("deletedDate", LocalDateTime.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<LocalDateTime> MODIFIED_DATE = Property.create("modifiedDate", LocalDateTime.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> PHOTO_URL = Property.create("photoUrl", String.class);
    public static final Property<String> SHORT_DESCRIPTION = Property.create("shortDescription", String.class);
    public static final Property<List<DbSpeakerArticles>> SPEAKER_TO_ARTICLES = Property.create("speakerToArticles", List.class);
    public static final Property<List<DbSpeakerEvents>> SPEAKER_TO_EVENTS = Property.create("speakerToEvents", List.class);
    public static final Property<List<DbSpeakerVideos>> SPEAKER_TO_VIDEO = Property.create("speakerToVideo", List.class);

    public void setCountry(String country) {
        writeProperty("country", country);
    }
    public String getCountry() {
        return (String)readProperty("country");
    }

    public void setCountryFlagCode(String countryFlagCode) {
        writeProperty("countryFlagCode", countryFlagCode);
    }
    public String getCountryFlagCode() {
        return (String)readProperty("countryFlagCode");
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        writeProperty("createdDate", createdDate);
    }
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime)readProperty("createdDate");
    }

    public void setDeletedDate(LocalDateTime deletedDate) {
        writeProperty("deletedDate", deletedDate);
    }
    public LocalDateTime getDeletedDate() {
        return (LocalDateTime)readProperty("deletedDate");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setModifiedDate(LocalDateTime modifiedDate) {
        writeProperty("modifiedDate", modifiedDate);
    }
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime)readProperty("modifiedDate");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPhotoUrl(String photoUrl) {
        writeProperty("photoUrl", photoUrl);
    }
    public String getPhotoUrl() {
        return (String)readProperty("photoUrl");
    }

    public void setShortDescription(String shortDescription) {
        writeProperty("shortDescription", shortDescription);
    }
    public String getShortDescription() {
        return (String)readProperty("shortDescription");
    }

    public void addToSpeakerToArticles(DbSpeakerArticles obj) {
        addToManyTarget("speakerToArticles", obj, true);
    }
    public void removeFromSpeakerToArticles(DbSpeakerArticles obj) {
        removeToManyTarget("speakerToArticles", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbSpeakerArticles> getSpeakerToArticles() {
        return (List<DbSpeakerArticles>)readProperty("speakerToArticles");
    }


    public void addToSpeakerToEvents(DbSpeakerEvents obj) {
        addToManyTarget("speakerToEvents", obj, true);
    }
    public void removeFromSpeakerToEvents(DbSpeakerEvents obj) {
        removeToManyTarget("speakerToEvents", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbSpeakerEvents> getSpeakerToEvents() {
        return (List<DbSpeakerEvents>)readProperty("speakerToEvents");
    }


    public void addToSpeakerToVideo(DbSpeakerVideos obj) {
        addToManyTarget("speakerToVideo", obj, true);
    }
    public void removeFromSpeakerToVideo(DbSpeakerVideos obj) {
        removeToManyTarget("speakerToVideo", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbSpeakerVideos> getSpeakerToVideo() {
        return (List<DbSpeakerVideos>)readProperty("speakerToVideo");
    }


}
