package com.thelak.database.entity.auto;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.thelak.database.entity.DbVideoFavorites;
import com.thelak.database.entity.DbVideoHistory;
import com.thelak.database.entity.DbVideoTimecode;

/**
 * Class _DbVideo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbVideo extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> CATEGORY = Property.create("category", String.class);
    public static final Property<String> CONTENT_URL = Property.create("contentUrl", String.class);
    public static final Property<String> COUNTRY = Property.create("country", String.class);
    public static final Property<String> COVER_URL = Property.create("coverUrl", String.class);
    public static final Property<LocalDateTime> CREATED_DATE = Property.create("createdDate", LocalDateTime.class);
    public static final Property<LocalDateTime> DELETED_DATE = Property.create("deletedDate", LocalDateTime.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<String> DURATION = Property.create("duration", String.class);
    public static final Property<LocalDateTime> MODIFIED_DATE = Property.create("modifiedDate", LocalDateTime.class);
    public static final Property<String> PARTNER_LOGO_URL = Property.create("partnerLogoUrl", String.class);
    public static final Property<String> SPEAKER = Property.create("speaker", String.class);
    public static final Property<String> SPEAKER_INFORMATION = Property.create("speakerInformation", String.class);
    public static final Property<String> TITLE = Property.create("title", String.class);
    public static final Property<Integer> YEAR = Property.create("year", Integer.class);
    public static final Property<List<DbVideoFavorites>> VIDEO_TO_FAVORITE = Property.create("videoToFavorite", List.class);
    public static final Property<List<DbVideoHistory>> VIDEO_TO_HISTORY = Property.create("videoToHistory", List.class);
    public static final Property<List<DbVideoTimecode>> VIDEO_TO_TIMECODE = Property.create("videoToTimecode", List.class);

    public void setCategory(String category) {
        writeProperty("category", category);
    }
    public String getCategory() {
        return (String)readProperty("category");
    }

    public void setContentUrl(String contentUrl) {
        writeProperty("contentUrl", contentUrl);
    }
    public String getContentUrl() {
        return (String)readProperty("contentUrl");
    }

    public void setCountry(String country) {
        writeProperty("country", country);
    }
    public String getCountry() {
        return (String)readProperty("country");
    }

    public void setCoverUrl(String coverUrl) {
        writeProperty("coverUrl", coverUrl);
    }
    public String getCoverUrl() {
        return (String)readProperty("coverUrl");
    }

    public void setCreatedDate(LocalDateTime createdDate) {
        writeProperty("createdDate", createdDate);
    }
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime)readProperty("createdDate");
    }

    public void setDeletedDate(LocalDateTime deletedDate) {
        writeProperty("deletedDate", deletedDate);
    }
    public LocalDateTime getDeletedDate() {
        return (LocalDateTime)readProperty("deletedDate");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setDuration(String duration) {
        writeProperty("duration", duration);
    }
    public String getDuration() {
        return (String)readProperty("duration");
    }

    public void setModifiedDate(LocalDateTime modifiedDate) {
        writeProperty("modifiedDate", modifiedDate);
    }
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime)readProperty("modifiedDate");
    }

    public void setPartnerLogoUrl(String partnerLogoUrl) {
        writeProperty("partnerLogoUrl", partnerLogoUrl);
    }
    public String getPartnerLogoUrl() {
        return (String)readProperty("partnerLogoUrl");
    }

    public void setSpeaker(String speaker) {
        writeProperty("speaker", speaker);
    }
    public String getSpeaker() {
        return (String)readProperty("speaker");
    }

    public void setSpeakerInformation(String speakerInformation) {
        writeProperty("speakerInformation", speakerInformation);
    }
    public String getSpeakerInformation() {
        return (String)readProperty("speakerInformation");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setYear(int year) {
        writeProperty("year", year);
    }
    public int getYear() {
        Object value = readProperty("year");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToVideoToFavorite(DbVideoFavorites obj) {
        addToManyTarget("videoToFavorite", obj, true);
    }
    public void removeFromVideoToFavorite(DbVideoFavorites obj) {
        removeToManyTarget("videoToFavorite", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbVideoFavorites> getVideoToFavorite() {
        return (List<DbVideoFavorites>)readProperty("videoToFavorite");
    }


    public void addToVideoToHistory(DbVideoHistory obj) {
        addToManyTarget("videoToHistory", obj, true);
    }
    public void removeFromVideoToHistory(DbVideoHistory obj) {
        removeToManyTarget("videoToHistory", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbVideoHistory> getVideoToHistory() {
        return (List<DbVideoHistory>)readProperty("videoToHistory");
    }


    public void addToVideoToTimecode(DbVideoTimecode obj) {
        addToManyTarget("videoToTimecode", obj, true);
    }
    public void removeFromVideoToTimecode(DbVideoTimecode obj) {
        removeToManyTarget("videoToTimecode", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbVideoTimecode> getVideoToTimecode() {
        return (List<DbVideoTimecode>)readProperty("videoToTimecode");
    }


}
